modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"
[[mods]]
modId="prisonutilmod"
version="${file.jarVersion}"
displayName="PrisonUtilMod"
authors="Tijsdieman"
description='''
Provides features for prison servers
'''
[[dependencies.prisonutilmod]]
   modId="forge"
   mandatory=true
   versionRange="[40,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.prisonutilmod]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.18.2,1.19)"
   ordering="NONE"
   side="BOTH"
